### PR TITLE
update atom.dart package references

### PR DESCRIPTION
**Pull request by danrubel**
@devoncarew

### CODE REVIEW

**Comment by devoncarew** [comment]
lgtm, but I think the travis failure here is legitimate (not a strong mode thing)

**Comment by danrubel** [comment]
Took a couple iterations, but now fixed.

**Comment by devoncarew** [comment]
lgtm!

**Comment by danrubel** [comment]
Merged https://github.com/flutter/atom-flutter/commit/d992cd1b3cc2e6dcb13507bc55fe8296be2c95a6

**Pull request closed without merging**
